---
title: "dark-mode.Rmd"
subtitle: "Basic dark mode with DT and Highcharter, see post at https://thomasswilliams.github.io/development/r/2022/08/26/r-markdown-dark-mode-1.html"
author: "Thomas Williams <https://github.com/thomasswilliams>"
output:
  html_document:
    theme: default
runtime: shiny
---

Tested with the R Markdown `default`, `spacelab`, `bootstrap` and `darkly` themes.

``` {r global, echo = FALSE, message = FALSE, warning = FALSE}
# reference a couple of packages for demo
library(jsonlite)
# DataTable
# https://rstudio.github.io/DT/
library(DT)
# Highcharter wrapper for Highcharts
# https://jkunst.com/highcharter/
library(highcharter)
```

Size of RStudio daily builds by platform from <https://dailies.rstudio.com/rstudio/latest/index.json>

```{r, echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE, cache.extra = Sys.Date()}
# get JSON from RStudio latest daily builds, cache for 1 day
raw_json <- jsonlite::fromJSON(
  "https://dailies.rstudio.com/rstudio/latest/index.json",
  simplifyVector = FALSE
)

# get just the collection of platforms for RStudio Desktop
# may be different from when I retrieved it in mid-August 2022
# adapted from https://themockup.blog/posts/2020-12-13-extracting-json-from-websites-and-public-apis-with-r/
platforms <- raw_json[["products"]][["electron"]][["platforms"]]

# make collection of platforms into a dataframe
# using "tibble" from TidyVerse
df <- platforms %>%
  tibble::enframe() %>%
  # set attribute name as column name, value as value
  tidyr::unnest_auto(value) %>%
  # create a new column by joining OS and platform from "name...1" and "name...2"
  tidyr::unite(name, c(name...2, name...1), sep = " ") %>%
  # keep just the columns we want, name and size in bytes
  dplyr::select(name, size)
```

```{r, echo = FALSE}
# placeholder for datatable
DT::dataTableOutput("table", width = "100%", height = "auto")
# output placeholder for highchart
# adapted from https://github.com/jbkunst/highcharter-shiny/blob/master/01-get-started/app.R
highcharter::highchartOutput("chart")

# render data table
output$table <- DT::renderDataTable({
  # create a very basic datatable of OS name, size
  dt <- DT::datatable(
    df,
    # no selection
    selection = "none",
    # options
    options = list(
      # only include table and number of records in output
      dom = "it",
      # number of records visible (should be all)
      pageLength = 9999L
    ))
  # return datatable
  return(dt)
})

# render chart
output$chart <- highcharter::renderHighchart({
  # create a column chart
  highcharter::highchart() %>%
    highcharter::hc_chart(type = "column") %>%
    # x axis is name
    highcharter::hc_xAxis(categories = df$name) %>%
    # y axis is bytes
    highcharter::hc_add_series(
      name = "Size",
      data = df$size
    ) %>%
    # no legend (single series only)
    highcharter::hc_legend(
      enabled = FALSE
    )
})
```

Below is the CSS used in this example:

```{css}
/* specific colors for light and dark mode
   adapted from https://radek.io/posts/secret-darkmode-toggle/ */
:root {
  --background-color: #ffffff;
  --font-color: #24272B;
  /* can set other variables here as needed e.g. secondary font, secondary background etc. */
}
/* detect user preference colors
   adapted from https://radek.io/posts/secret-darkmode-toggle/ */
@media (prefers-color-scheme: dark) {
  :root {
    --background-color: #24272B;
    --font-color: #f6f6f6;
  }
  /* any styles that should just apply to dark mode can be added here */
  /* hacky dark mode code blocks */
  pre {
    filter: invert(0.8);
  }
  /* make striped rows less conspicuous 
     depending on version of data tables, may need one or more of the following selectors */
  .table-striped > tbody > tr:nth-of-type(odd),
  table.dataTable.stripe tbody tr.odd,
  table.dataTable.display tbody tr.odd {
    background-color: #f9f9f911;
  }
  /* hover rows less conspicuous */
  .table-hover > tbody > tr:hover,
  table.dataTable.hover tbody tr:hover,
  table.dataTable.display tbody tr:hover {
    background-color: #f5f5f522 !important;
  }
}

/* override colors in R Markdown theme, with variables */
body {
  /* colors from variables - need "!important" so takes priority over settings elsewhere */
  background: var(--background-color) !important;
  color: var(--font-color) !important;
}
/* headings */
h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
  color: var(--font-color) !important;
}

/* data tables div */
div.datatables {
  color: var(--font-color) !important;
}
/* table rows */
table.dataTable tbody tr {
  background-color: var(--background-color);
}
/* number of records */
.dataTables_info {
  color: var(--font-color) !important;
}
```