---
title: "reload-data.Rmd"
subtitle: "Reload parameters on button click without full page reload, see blog post at  https://thomasswilliams.github.io/development/r/2022/09/22/r-markdown-reload-parameter-with-button.html"
author: "Thomas Williams <https://github.com/thomasswilliams>"
output:
  html_document:
    theme: default
runtime: shiny
---

```{r global, echo = FALSE, message = FALSE, warning = FALSE}
# load packages
# A Simple and Robust JSON Parser and Generator for R
# https://cran.r-project.org/package=jsonlite
library(jsonlite)
# dplyr for piping with "%>%"
library(dplyr)
# htmltools (part of Shiny)
library(htmltools)
```

The user parameter will be displayed after getting data from an API. Click "reload" to load different users from the API.

```{r, echo = FALSE}
# create empty data frame for user parameter, with columns matching what we will fetch from API
# as this empty "users" variable exists outside render event, can be used elsewhere on page
users <- data.frame(
  username = character(),
  email = character(),
  phone_number = character(),
  stringsAsFactors = FALSE
)

# placeholder for user parameter (div)
shiny::uiOutput("user_select_div")

# placeholder for refresh button
# note icons need "icon()" as per https://shiny.rstudio.com/reference/shiny/0.14/icon.html
shiny::actionButton("refreshbutton", "Reload", icon = shiny::icon("arrows-rotate"))

# render user parameter (dropdown), inside a div
# note the dropdown will be rendered *after* the API call finishes
output$user_select_div <- shiny::renderUI({
  # render function is dependent on "refresh" button, so when refresh button is
  # clicked, select will be re-rendered (this code will be run)
  input$refreshbutton
  # get 5 random users from API using jsonlite and set to global variable using
  # "<<-" (double arrow assignment) notation
  # "flatten" into data frame (default is list of lists)
  users <<- jsonlite::fromJSON(
    "https://random-data-api.com/api/v2/users?size=5&response_type=json",
    flatten = TRUE
  ) %>%
    # keep just the columns we want
    # for all possible fields from the API, see https://random-data-api.com/api/v2/users
    dplyr::select(username, email, phone_number)

  # test if we got any results, if zero leave and return message
  # adapted from https://stackoverflow.com/a/59394360
  shiny::validate(
    shiny::need((nrow(users) != 0L), "No data available")
  )

  # create the actual dropdown control to select user
  # can be referenced elsewhere on the page as "input$user"
  shiny::selectInput(
    "user",
    label = "Select a user",
    # display user name (don't show e-mail, phone number, any other fields)
    choices = users$username,
    # not Selectize
    selectize = FALSE
  )
})
```
 
<br>
You have selected:
```{r, echo = FALSE}
# placeholder for output text of selected user
# of course, instead of text, this could be used in anything: table, chart, further API call etc.
shiny::uiOutput("output")
 
# render output text for the selected user
# note will not run immediately, as user select is being loaded when this page first loads
output$output <- shiny::renderUI({
  # make this render function also dependent on "refresh" button
  # not needed, but makes the output inactive while reloading
  input$refreshbutton

  # get just the single result from users data frame, based on selected username in dropdown
  # this will be a list with username, email, phone_number
  selected_user <- users[users$username == input$user, ]

  # make sure we've selected a user, test if the username field is empty
  shiny::validate(
    shiny::need(selected_user$username, "No user selected")
  )

  # for demo purposes only, just render simple HTML
  htmltools::pre(
    paste0("User: ", selected_user$username),
    paste0("E-mail: ", selected_user$email),
    paste0("Phone: ", selected_user$phone_number)
  )
})
```

<br>
Users are randomly generated by https://random-data-api.com/api/v2/users.

```{js, echo = FALSE}
// after a short delay when page loads (and API runs and returns), set focus to user select
// expects jQuery (as part of Shiny)
$(function() {
  setTimeout(function() {
    $("#user").focus();
  }, 1200);
});
```